# This is a basic workflow that is manually triggered

name: Update courses.yaml data

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update_courses_yml:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # We need Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    # We need to fetch the code where our courses.yaml generator lives
    - name: Fetch bi-app code
      uses: actions/checkout@v2
      with:
        repository: compsoc-edinburgh/bi-app
        path: bi-app
    
    # We obviously need to clone the betterinformatics repo itself
    - name: Clone our repository
      uses: actions/checkout@v2
      with:
        path: bi
    
    # Install the dependencies for the courses.yaml generator
    - name: Install dependencies
      run: |
        cd bi-app/courses.yaml
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Actually generate courses.yaml
    - name: Generate courses.yaml
      id: generate_yaml
      run: python bi-app/courses.yaml/app.py --auto-yaml bi/_data/courses.yaml
    
    # Push the new courses.yaml file to master
    - name: Push courses.yaml
      if: steps.generate_yaml.outputs.has_changed == "true"
      run: |
        cd bi
        
        git config user.name "Better Informatics"
        
        # The number ID in the email comes from https://api.github.com/users/better-informatics%5Bbot%5D
        # Which is not an actual user account. It's a bot:
        # - https://github.com/organizations/compsoc-edinburgh/settings/apps/better-informatics
        #
        # See this for more information: https://github.community/t/github-actions-bot-email-address/17204/5
        git config user.email "42103905+better-informatics[bot]@users.noreply.github.com"
        
        git add courses.yaml
        git commit -m "Automatically update courses.yaml"
        git push origin master
