on: push
jobs:
  main:
    runs-on: windows-2019
    steps:
      - name: get version
        run: powershell -Command Get-Host
      - name: ya
        run: echo 'hi' > hi && powershell -Command (Get-FileHash hi -Algorithm SHA256).Hash
